
# MANDATORY SITE SETTINGS
# =======================

sass:
  sass_dir: css
  style: compressed
  exclude: []

livereload: true
baseurl: ""

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

url: https://boldcode.io
title: Bold Code 
email: contact@boldcode.io
description: "L'outsourcing IT éthique, au Népal"


# JEKYLL PLUGINS
# ==============

# Jekyll SEO plugin
lang: fr_FR
twitter:
    username: boldcode_io
logo: /img/logos/logo-DT-color-blackbg.256p.png
image: 
    path: /img/logos/logo-DT-color-blackbg.256p.png

# JEKYLL TEMPLATE
# ===============

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/boldcode_io 
    username: "@boldcode_io"
  - title: facebook
    url: https://www.facebook.com/boldcode/
    username: "/boldcode"

# Postal address (add as many lines as necessary)
address:
  - line: Fécamp
  - line: Fécamp

# Build settings
markdown: kramdown
permalink: pretty
# permalink: contact

